version: "3"

services:
  chat:
    build: .
    container_name: chat
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - chat-database
      - chat-database-express

  chat-database:
    image: mongo
    container_name: chat-database
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  chat-database-express:
    image: mongo-express
    container_name: chat-database-interface-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: chat-database
    depends_on:
      - chat-database
